name: mock CI/CD

on:
  push:
    branches:
      - 'feature/*'
    paths:
      - alpha/**
      - beta/**
      - gamma/**
  pull_request:
    branches:
      - 'release/*'
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List modified files
      run: |
        echo "The following files were modified in this commit:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}