name: mock CI/CD

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'release/*'
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'main'))
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get commit message and branch name
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Branch: $BRANCH_NAME" > commit_info.txt
        echo "Commit message: $COMMIT_MESSAGE" >> commit_info.txt

    - name: Display commit information
      run: cat commit_info.txt

    - name: Create build artifact
      run: |
        echo "Mock build complete."
        mv commit_info.txt file_build.txt

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: file_build.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: .

    - name: Rename build artifact
      run: mv file_build.txt file_deploy.txt

    - name: Upload deploy artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy
        path: file_deploy.txt
  build_deploy_status:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Check Deployment Status
      run: |
        echo "Deployment is successful"
      shell: bash