name: mock CI/CD

on:
  workflow_dispatch: 
  push:
    branches:
      - 'feature/*'
    paths:
      - alpha/**
      - beta/**
      - gamma/**
  pull_request:
    branches:
      - 'release/*'
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history

    - name: Get base branch
      id: base_branch
      run: |
        echo "::set-output name=BASE_BRANCH::$(git merge-base origin/main HEAD)"

    - name: List all modified files in the branch
      run: |
        echo "The following files were modified in this branch:"
        git diff --name-only ${{ steps.base_branch.outputs.BASE_BRANCH }} ${{ github.sha }}
