name: mock CI/CD

on:
  push:
    branches:
      - 'feature/*'
    paths:
      - alpha/**
      - beta/**
      - gamma/**
  pull_request:
    branches:
      - 'release/*'
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depath: 0

    - name: Get the list of modified files
      run: |
        echo "The following files were modified in this commit:"
        git diff --name-only $(git rev-parse HEAD^) $(git rev-parse HEAD)
  